var mongoose = require('mongoose')

var Lang = require('../models/lang')

const config = require('../config/database')

mongoose.connect(config.database)

// On Connection
mongoose.connection.on('connected', () => {
  console.log('Connected to mongo server')
});

// On Error
mongoose.connection.on('error', (err) => {
  console.log('Database error: '+err)
});

var option_pl = {
  "name_short": "pl",
  "name_full": "Polski",
  "title": "Time Saver - BCWEB.PL",
  "home": "Home",
  "profile": "Profile",
  "my_logs": "Moje zapisy",
  "log_out": "Wyloguj się",
  "log_in": "Zaloguj się",
  "registration": "Rejestracja",
  "dashboard": "Dashboard",
  "settings": "Settings",
  "logs_operations": "Operacje nad logami",
  "log_added": "Dodano nowy zapis. Teraz możesz pracować.",
  "log_finished": "Teraz praca jest skończona.",
  "logs_limit": "Twój limit zapisów się skończył.",
  "not_logged_in": "Nie jesteś zalogowany",
  "logged_in": "Jesteś zalogowany",
  "logged_out": "Jesteś wylogowany",
  "click_start": "Kliknij żeby rozpocząć pracę",
  "click_end": "Kliknij żeby skończyć pracę",
  "unclickable": "Na dzisiaj praca jest skończona",
  "profile_desc": "Witamy na swojej stronie profilu",
  "my_logs_desc": "Witamy w zapisach",
  "all_logs": "Wszystkie zapisy",
  "logs_users": "Zapisy użytkowników",
  "logs_by_month": "Zapisy według miesięcy",
  "logs_by_user": "Zapisy użytkownika ",
  "logs_by_user_desc": "Witamy w zapisach według użytkownika ",
  "un_req": "Wymagana jest nazwa użytkownika",
  "pass_req": "Wymagane jest hasło",
  "pass_d_match": "Hasła nie pasują do siebie",
  "date_req": "Wymagana jest data",
  "status_req": "Wymagany jest status",
  "time_start_req": "Wymagany jest czas startu logowania",
  "time_over_req": "Wymagany jest czas końcu logowania",
  "user_exist": "Podana nazwa użytkownika już istnieje",
  "registered": "Jesteś zarejestrowany i możesz się zalogować",
  "user_unknown": "Nieznany użytkownik",
  "inv_pass": "Nieprawidłowe hasło",
  "log_exist": "Log takiej daty i użytkownika już istnieje",
  "log_export": "Plik wyeksportowany",
  "log_notexist": "Log o takiej dacie i nazwie użytkownika nie istnieje",
  "log_changed": "Log został zmieniony",
  "username_changed": "Nazwa użytkownika została zmieniona",
  "error_username_change": "Nazwa użytkownika nie została zmieniona",
  "log_added_auto": "Log został dodany",
  "month_req": "Miesiąc jest wymagany",
  "year_req": "Rok jest wymagany",
  "export_failed": "Eksportowanie nie powiodło się. Sprawdź nazwe użytkownika albo datę",
  "not_good_ip": "Przepraszamy ale twój ip jest nie poprawny",
  "settings_desc": "Tu możesz wprowadzać zmiany do systemu",
  "edit_users": "Edytowanie użytkowników",
  "edit_users_desc": "Tutaj możesz zmienić nazwe użytkownika",
  "sign_up": "Please Sign Up",
  "sign_in": "Please Sign In",
  "submit": "Submit",
  "add_log_title": "Dodawanie logów",
  "add_log_desc": "Tutaj możesz dodać nowy log",
  "edit_log_title": "Edytowanie logów",
  "edit_log_desc": "Tutaj możesz zmienić dowolny log",
  "username": "Username:",
  "select_username": "Select username:",
  "new_username": "New username:",
  "status": "Status:",
  "status_started": "started",
  "status_overed": "overed",
  "date_text": "Date:",
  "time_start": "Time Start:",
  "time_over": "Time Over:",
  "time_plus": "Time Plus:",
  "month": "Month:",
  "year": "Year",
  "sum_time": "Sum time:",
  "sub_hours": "Suma godzin:",
  "export_logs_title": "Exportowanie logów",
  "export_logs_desc": "Tutaj możesz wyeksportować logi według użytkownika i miesiąca",
  "error_404_title": "Błąd 404",
  "error_404_desc": "Strona nie jest dostępna",
  "logs": "Operację nad logami",
  "logs_desc": "Tutaj możesz wykonywać operację nad logami",
  "new_username_req": "Wpisz nową nazwę użytkownika",
  "edit_langs": "Edytowanie langów",
  "edit_langs_desc": "Tutaj możesz zmieniać langi",
  "langs_changed": "Langi zostały zmienione",
  "error_langs_change": "Langi nie zostały zmienione",
  "language": "Język",
  "language_changed": "Język został zmieniony",
  "error_language_change": "Język nie został zmieniony",
  "edit_blocking": "Edytowanie blokowania",
  "edit_blocking_desc": "Tutaj możesz edytować blokowanie",
  "blocking_is_on": "Blokowanie włączone",
  "blocking_is_off": "Blokowanie wyłączone",
  "bloking_changed": "Blokowanie zostało zmienione",
  "summary_logs": "Zbiorcza lista logów",
  "add_time_plus": "Dodać nadgodziny",
  "add_time_plus_desc": "Tu możesz dodać nadgodziny",
  "plus_time": "Czas nadgodzin",
  "plus_desc": "Opis nadgodzin",
  "time_plus_added": "Nadgodziny zostały dodane",
  "time_plus_exist": "Log o takiej dacie nie instnieje",
  "plus_time_req": "Wymagany jest czas nadgodzin",
  "plus_desc_req": "Wymagany jest opis nadgodzin"
}

var option_en = {
  "name_short": "en",
  "name_full": "English",
  "title": "Time Saver - BCWEB.PL",
  "home": "Home",
  "profile": "Profile",
  "my_logs": "My logs",
  "log_out": "Log out",
  "log_in": "Log in",
  "registration": "Registration",
  "dashboard": "Dashboard",
  "settings": "Settings",
  "logs_operations": "Operacje nad logami",
  "log_added": "Your new log added. Now you can work.",
  "log_finished": "Teraz praca jest skończona.",
  "logs_limit": "Your limit of logs is over.",
  "not_logged_in": "You are not logged in",
  "logged_in": "You are logged in",
  "logged_out": "You are logged out",
  "click_start": "Press to start",
  "click_end": "Press to end",
  "unclickable": "Today work is over",
  "profile_desc": "Welcome to your profile page",
  "my_logs_desc": "Welcome to your logs",
  "all_logs": "All logs",
  "logs_users": "Zapisy użytkowników",
  "logs_by_month": "Logs by month",
  "logs_by_user": "Logs of ",
  "logs_by_user_desc": "Welcome to logs of ",
  "un_req": "Username is required",
  "pass_req": "Password is required",
  "pass_d_match": "Passwords do not match",
  "user_exist": "Given username already exists",
  "registered": "You are registered and can now login",
  "user_unknown": "Unknown User",
  "inv_pass": "Invalid password",
  "date_req": "Wymagana jest data",
  "status_req": "Wymagany jest status",
  "time_start_req": "Wymagany jest czas startu logowania",
  "time_over_req": "Wymagany jest czas końcu logowania",
  "log_exist": "Log takiej daty i użytkownika już istnieje",
  "log_export": "Plik wyeksportowany",
  "log_notexist": "Log o takiej dacie i nazwie użytkownika nie istnieje",
  "log_changed": "Log został zmieniony",
  "username_changed": "Nazwa użytkownika została zmieniona",
  "error_username_change": "Nazwa użytkownika nie została zmieniona",
  "log_added_auto": "Log został dodany",
  "month_req": "Miesiąc jest wymagany",
  "year_req": "Rok jest wymagany",
  "export_failed": "Eksportowanie nie powiodło się. Sprawdź nazwe użytkownika albo datę",
  "not_good_ip": "Przepraszamy ale twój ip jest nie poprawny",
  "settings_desc": "Tu możesz wprowadzać zmiany do systemu",
  "edit_users": "Edytowanie użytkowników",
  "edit_users_desc": "Tutaj możesz zmienić nazwe użytkownika",
  "sign_up": "Please Sign Up",
  "sign_in": "Please Sign In",
  "submit": "Submit",
  "add_log_title": "Dodawanie logów",
  "add_log_desc": "Tutaj możesz dodać nowy log",
  "edit_log_title": "Edytowanie logów",
  "edit_log_desc": "Tutaj możesz zmienić dowolny log",
  "username": "Username:",
  "select_username": "Select username:",
  "new_username": "New username:",
  "status": "Status:",
  "status_started": "started",
  "status_overed": "overed",
  "date_text": "Date:",
  "time_start": "Time Start:",
  "time_over": "Time Over:",
  "time_plus": "Time Plus:",
  "month": "Month:",
  "year": "Year",
  "sum_time": "Sum time:",
  "sub_hours": "Suma godzin:",
  "export_logs_title": "Exportowanie logów",
  "export_logs_desc": "Tutaj możesz wyeksportować logi według użytkownika i miesiąca",
  "error_404_title": "Błąd 404",
  "error_404_desc": "Strona nie jest dostępna",
  "logs": "Operację nad logami",
  "logs_desc": "Tutaj możesz wykonywać operację nad logami",
  "new_username_req": "Wpisz nową nazwę użytkownika",
  "edit_langs": "Edytowanie langów",
  "edit_langs_desc": "Tutaj możesz zmieniać langi",
  "langs_changed": "Langi zostały zmienione",
  "error_langs_change": "Langi nie zostały zmienione",
  "language": "Language",
  "language_changed": "Język został zmieniony",
  "error_language_change": "Język nie został zmieniony",
  "edit_blocking": "Edytowanie blokowania",
  "edit_blocking_desc": "Tutaj możesz edytować blokowanie",
  "blocking_is_on": "Blokowanie włączone",
  "blocking_is_off": "Blokowanie wyłączone",
  "bloking_changed": "Blokowanie zostało zmienione",
  "summary_logs": "Summary logs",
  "add_time_plus": "Dodać nadgodziny",
  "add_time_plus_desc": "Tu możesz dodać nadgodziny",
  "plus_time": "Czas nadgodzin",
  "plus_desc": "Opis nadgodzin",
  "time_plus_added": "Nadgodziny zostały dodane",
  "time_plus_exist": "Log o takiej dacie nie instnieje",
  "plus_time_req": "Wymagany jest czas nadgodzin",
  "plus_desc_req": "Wymagany jest opis nadgodzin"
}

function addNewLanguage(option){
  var newLang = new Lang(option)

  Lang.createLang(newLang, (err, lang) => {
    if(err) throw err
    console.log(lang)
  })
}

addNewLanguage(option_pl)
addNewLanguage(option_en)
